MULTISITE-10691: fix error (conflict resolution)
error: Exception: Cannot initialize entity translation path variables (invalid path scheme). in EntityTranslationDefaultHandler->initPathVariables() (line 1711 of /ec/dev/server/fpfis/webroot/sources/gervase/repositories/subsites/farnet-dev/platform/profiles/multisite_drupal_standard/modules/contrib/entity_translation/includes/translation.handler.inc).